version: "3.7"

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /usr/local/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /usr/local/caddy/caddy_data:/data

networks:
  caddy:

volumes:
  caddy_data: {}