services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    depends_on:
      - zigbee2mqtt
    volumes:
      - /usr/local/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /usr/local/homeassistant/media:/media
    restart: unless-stopped
    privileged: true
    network_mode: host

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - /usr/local/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=Europe/Paris
    devices:
    # Make sure this matched your adapter location
      - /dev/ttyS1:/dev/ttyACM0
    network_mode: host

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /usr/local/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /usr/local/caddy/caddy_data:/data

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    network_mode: host
    volumes:
      - /usr/local/nvme/jellyfin:/config
      - /usr/local/nvme/series:/data/tvshows
      - /usr/local/nvme/movies:/data/movies
    restart: unless-stopped

  samba:
    image: dperson/samba
    container_name: samba
    environment:
      - TZ=/etc/timezone:/etc/timezone:ro
    network_mode: host
    restart: unless-stopped
    stdin_open: true
    tty: true
    pid: host
    volumes:
      - /usr/local/nvme/:/share
      - /usr/local/samba/smb.conf:/etc/samba/smb.conf

  avahi:
    image: epandi/avahi
    container_name: avahi
    volumes:
      - /usr/local/avahi/services/:/etc/avahi/services
    restart: unless-stopped
    network_mode: host

  db:
    image: mariadb:10.5
    container_name: nextcloud-mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /usr/local/nvme/nextcloud/nextcloud-data-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    privileged: true

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    ports:
     - 8092:80
    links:
     - db
    depends_on:
      - db
    volumes:
      - /usr/local/nvme/nextcloud/nextcloud-data/:/var/www/html
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=example.com
      - MYSQL_HOST=nextcloud-mariadb
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=mysql
    privileged: true

  domoticz:
    image: domoticz/domoticz:stable
    container_name: domoticz
    restart: unless-stopped
    #devices:
     #- /dev/ttyUSB0:/dev/ttyUSB0
    ports:
      - 8080:8080
    volumes:
      - /usr/local/domoticz:/opt/domoticz/userdata
    environment:
      - TZ=Europe/Paris

  homebridge:
    image: oznu/homebridge:raspberry-pi
    container_name: homebridge
    restart: always
    network_mode: host
    volumes:
      - /usr/local/homebridge:/homebridge
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    
  resticprofile:
    image: creativeprojects/resticprofile:latest
    container_name: resticprofile
    entrypoint: '/bin/sh'
    command:
      - '-c'
      - 'resticprofile schedule --all && crond -f'
    volumes:
      - /usr/local/resticprofile/profiles.yaml:/etc/resticprofile/profiles.yaml:ro
      - /usr/local/resticprofile/key:/etc/resticprofile/key:ro
      - /usr/local/homeassistant:/homeassistant
      - /usr/local/caddy:/caddy
      - /usr/local/mapio:/mapio
      - /usr/local/zigbee2mqtt:/zigbee2mqtt
    environment:
      - TZ=Europe/Paris

  wireguard:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wireguard
    restart: unless-stopped
    sysctls:
        - net.ipv4.ip_forward=1
        - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
        - SYS_MODULE
        - NET_ADMIN
    ports:
        - '51821:51821/tcp'
        - '51820:51820/udp'
    volumes:
        - '/usr/local/wireguard:/etc/wireguard'
    environment:
        # Required:
        # Change this to your host's public address
        - WG_HOST=mapio.local
        # Optional:
        - PASSWORD_HASH=$$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG # (needs double $$, hash of 'foobar123')

  otbr:
    container_name: otbr
    image: ghcr.io/iotheque/mapio-otbr-docker:1.0.0
    restart: unless-stopped
    privileged: true
    network_mode: host
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    environment:
      DEVICE: "/dev/ttyAMA5"
      # Change according to your internet connection method
      BACKBONE_IF: wlan0
      FLOW_CONTROL: 0
      FIREWALL: 0
      NAT64: 1
      BAUDRATE: 115200
      OTBR_REST_PORT: 8081
      OTBR_WEB_PORT: 7586
      AUTOFLASH_FIRMWARE: 0
    devices:
      # Change according the RF slot
      - /dev/ttyAMA5:/dev/ttyAMA5
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /usr/local/otbr_data:/var/lib/thread

  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    restart: unless-stopped
    network_mode: host
    privileged: true
    depends_on:
      - otbr
    security_opt:
      - apparmor:unconfined
    volumes:
      - /usr/local/matter_data:/data/
      - /run/dbus:/run/dbus:ro
      - /etc/localtime:/etc/localtime:ro
    # Change according to your internet connection method
    command: >
      --storage-path /data
      --paa-root-cert-dir /data/credentials
      --bluetooth-adapter 0
      --log-level-sdk progress
      --primary-interface wlan0

networks:
  caddy:

volumes:
  caddy_data: {}
  nextcloud:
  db: