version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /usr/local/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - /usr/local/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=Europe/Berlin
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    network_mode: host

  nginx:
    container_name: nginx
    image: nginx
    privileged: true
    network_mode: host
    volumes:
       - /usr/local/nginx/default.conf:/etc/nginx/conf.d/default.conf
       - /usr/local/nginx/certs:/usr/local/certificates
    restart: unless-stopped