---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    network_mode: host
    volumes:
      - /usr/local/nvme/jellyfin:/config
      - /usr/local/nvme/series:/data/tvshows
      - /usr/local/nvme/movies:/data/movies
    restart: unless-stopped