version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.5
    container_name: nextcloud-mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /usr/local/nvme/nextcloud/nextcloud-data-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    privileged: true

  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    restart: always
    ports:
     - 8092:80
    links:
     - db
    depends_on:
      - db
    volumes:
      - /usr/local/nvme/nextcloud/nextcloud-data/:/var/www/html
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=example.com
      - MYSQL_HOST=nextcloud-mariadb
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=mysql
    privileged: true
