version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.5
    container_name: nextcloud-mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /usr/local/nextcloud/nextcloud-data-db:/var/lib/mysql
    network_mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    privileged: true

  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    restart: always
    network_mode: host
    depends_on:
      - db
    volumes:
      - /usr/local/nextcloud/nextcloud-data/:/var/www/html
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.pierrickperso.ddnsfree.com
    privileged: true
