version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    privileged: true
    network_mode: host
    volumes:
       - ./default_server:/etc/nginx/conf.d/default.conf
       - /usr/local/certificates:/usr/local/certificates
    restart: unless-stopped
